### ISSUE TITLE
pygpu.gpuarray.GpuArrayException: Invalid value or operation: 0

### ISSUE THREAD

**Issue by mlprt** [Theano/libgpuarray#203] opened 2016-06-28 02:03 UTC
Initialization of GPU context fails. Seems not to be an issue with string handling as in #36.

```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File ".../python3.4/site-packages/theano/gpuarray/__init__.py", line 110, in <module>
    init_dev(config.device)
  File ".../python3.4/site-packages/theano/gpuarray/__init__.py", line 66, in init_dev
    single_stream=config.gpuarray.single_stream)
  File "pygpu/gpuarray.pyx", line 562, in pygpu.gpuarray.init (pygpu/gpuarray.c:8359)
  File "pygpu/gpuarray.pyx", line 508, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:7974)
  File "pygpu/gpuarray.pyx", line 965, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12332)
pygpu.gpuarray.GpuArrayException: Invalid value or operation: 0
```

Received in response to my first test of OpenCL support in Theano, like `THEANO_FLAGS=device=opencl0:0 python test.py`. With device specified instead as "opencl0:1", output is the same except `Invalid value or operation: 1`. Passing a malformed OpenCL name still returns `ValueError: OpenCL name incorrect. Should be opencl<int>:<int>`.

Imports of pygpu and pyopencl are fine. Same error is output for direct call `pygpu.gpuarray.init("pyopencl0:0")`, as expected. The results of `python pyopencl/examples/benchmark.py` are as expected for devices 0:0 (GPU) and 0:1 (CPU).

**Comment by livnev** [comment] 2016-07-11 23:03
I am experiencing the same bug after installing from master:
```
$ python -c "import pygpu; print pygpu.init('opencl0:1').devname"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pygpu/gpuarray.pyx", line 562, in pygpu.gpuarray.init (pygpu/gpuarray.c:8389)
  File "pygpu/gpuarray.pyx", line 508, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:7998)
  File "pygpu/gpuarray.pyx", line 965, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12421)
pygpu.gpuarray.GpuArrayException: Invalid value or operation: 1

```
 I have the following debian packages installed: beignet-opencl-icd, ocl-icd-libopencl1, python-pyopencl. Here is the output of clinfo also, if relevant: https://paste.debian.net/780474/

Please let me know if there is more testing I need to do to determine the nature of this bug.

**Comment by nouiz** [comment] 2016-07-12 13:09
The OpenCL status Theano is not usable in real code, as we are missing too
much operation. But the back-end should support it:

https://github.com/Theano/Theano/issues/2936

We aren't working on this (we don't need it and we don't have time for
this). So unless you are ready to spend a significant amount of time
working on it, I would not recommand using the OpenCL back-end.

**Comment by abergeron** [comment] 2016-07-12 16:08
This error message means that the specified OpenCL device does not exist (or is not useable).

It may be because you have more than one platform installed.  Try with `opencl1:0`.  If that doesn't get you anywhere then you might have to go through the code and see what exactly is triggering the error, because it works for me.

**Comment by livnev** [comment] 2016-07-12 23:27
I tried reinstalling the OpenCL libraries and libgpuarray and this problem went away (but other problems did arise). I think the OpenCL libs weren't being detected by cmake. Please disregard my contribution here...

**Comment by fabriciorsf** [comment] 2016-10-15 21:14
Maybe, this error can be caused by use of a wrong device name.
I was getting this same error because I was using 'opencl0:2', like many tutorials indicated about this installation.
You can check the correct name using any this commands:
```
# check first device
python -c "import pygpu; print(pygpu.init('opencl0:0').devname)"
# check second device
python -c "import pygpu; print(pygpu.init('opencl0:1').devname)"
# check third device (if you have)
python -c "import pygpu; print(pygpu.init('opencl0:2').devname)"
```
On my PC, the first device name is "Iceland" (a codename, reference to [Radeon R7 M260](https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units#Radeon_R5.2F7.2F9_M200_Series)), and the second device name is "Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz".

If you want, can see my script-tutorial:
https://gist.github.com/fabriciorsf/b911963d8b71987a236401c49f1b75d6

**Comment by nouiz** [comment] 2017-01-12 16:41
Closing as the last comment is probably the good answer and we don't have good opencl support for now.

**Closed by nouiz** 2017-01-12 16:41 UTC

**Comment by sahilrggupta** [comment] 2017-01-30 00:12
I am facing the same issue, when I try to import theano it says "Could not initialize pygpu, support disabled"
GpuArrayException: ('Unsupported operation', 5)", Someone please help

**Comment by abergeron** [comment] 2017-01-30 18:21
Can you open a new ticket and post more information (like the complete output from Theano).
