### ISSUE TITLE
pygpu.gpuarray.GpuArrayException: (b'malloc: No such file or directory', 6)

### ISSUE THREAD

**Issue by Kay1794** [Theano/libgpuarray#486] opened 2017-07-21 22:12 UTC
Hi all,
Just like the title said I could not pass the pygpu.test() when I ran in to those errors.
I don't know what happened and it seems there's no one has met the same problems. All the errors I met are in the same type.
Any help will be so appreciated!

`
ERROR: pygpu.tests.test_blas.test_rgemmBatch_3d(16, 16, 9, 16, 'float32', ('f', 'f', 'c'), (False, False), False, 1, True, True, 0.6, 0.6)

Traceback (most recent call last):
File "/home/rcf-proj/yz6/miniconda3/envs/corossion/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/rcf-proj/yz6/miniconda3/envs/corossion/lib/python3.6/site-packages/pygpu/tests/support.py", line 44, in f
func(*args, **kwargs)
File "/home/rcf-proj/yz6/miniconda3/envs/corossion/lib/python3.6/site-packages/pygpu/tests/test_blas.py", line 229, in rgemmBatch_3d
trans_b=trans[1], overwrite_c=overwrite)
File "pygpu/blas.pyx", line 209, in pygpu.blas.gemmBatch_3d (pygpu/blas.c:4366)
File "pygpu/blas.pyx", line 66, in pygpu.blas.pygpu_blas_rgemmBatch_3d (pygpu/blas.c:2327)
pygpu.gpuarray.GpuArrayException: (b'malloc: No such file or directory', 6)`

**Comment by abergeron** [comment] 2017-07-24 19:09
Which version of pygpu do you have?

Also which device are you using to test with?

**Comment by Kay1794** [comment] 2017-08-02 23:35
Hi, thanks for replying.
I use the newest version on a tesla k40.
The device works well when I am using pytorch so the cuda should already be set properly right?

**Comment by abergeron** [comment] 2017-08-03 15:31
Please tell me the exact version, "newest version" can mean different things depending on where you install it from and when you did your install.

Also a couple of other questions:
 - What is the version of cuda that you have installed?
 - Are you using the k40 through cuda or opencl?
 - Is the error reproducible?

**Comment by shawntan** [comment] 2017-09-11 18:36
I'm facing a similar problem as well. 
Version: 0.7.1+8.g342016c

I first came across this error using batch_tensordot, and I followed the problem all the way back to libgpuarray.
```
======================================================================
ERROR: pygpu.tests.test_blas.test_rgemmBatch_3d(1, 24, 7, 16, 'float32', ('c', 'c', 'c'), (True, False), False, 1, False, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/u/tanjings/.local/lib/python2.7/site-packages/pygpu-0.7.1+8.g342016c-py2.7-linux-x86_64.egg/pygpu/tests/support.py", line 44, in f
    func(*args, **kwargs)
  File "/u/tanjings/.local/lib/python2.7/site-packages/pygpu-0.7.1+8.g342016c-py2.7-linux-x86_64.egg/pygpu/tests/test_blas.py", line 229, in rgemmBatch_3d
    trans_b=trans[1], overwrite_c=overwrite)
  File "pygpu/blas.pyx", line 209, in pygpu.blas.gemmBatch_3d (pygpu/blas.c:4361)
  File "pygpu/blas.pyx", line 66, in pygpu.blas.pygpu_blas_rgemmBatch_3d (pygpu/blas.c:2322)
GpuArrayException: ('malloc: Resource temporarily unavailable', 6)
```

**Comment by shawntan** [comment] 2017-09-11 19:05
When running `DEVICE=cuda make test`, this error occurs during the `blas` test:
```
Running suite(s): blas
0%: Checks: 3, Failures: 3, Errors: 0
/u/tanjings/libgpuarray/tests/check_blas.c:43:F:all:test_gemmBatch_3d_C:0: Assertion 'GpuArray_rgemmBatch_3d(cb_no_trans, cb_no_trans, 1, &A, &B
, 0, &C, 1) == GA_NO_ERROR' failed: GpuArray_rgemmBatch_3d(cb_no_trans, cb_no_trans, 1, &A, &B, 0, &C, 1) == 6, GA_NO_ERROR == 0
/u/tanjings/libgpuarray/tests/check_blas.c:69:F:all:test_gemmBatch_3d_F:0: Assertion 'GpuArray_rgemmBatch_3d(cb_no_trans, cb_no_trans, 1, &A, &B, 0, &C, 0) == GA_NO_ERROR' failed: GpuArray_rgemmBatch_3d(cb_no_trans, cb_no_trans, 1, &A, &B, 0, &C, 0) == 6, GA_NO_ERROR == 0
/u/tanjings/libgpuarray/tests/check_blas.c:106:F:all:test_gemmBatch_3d_S:0: Assertion 'GpuArray_rgemmBatch_3d(cb_no_trans, cb_no_trans, 1, &A, &B, 0, &C, 1) == GA_NO_ERROR' failed: GpuArray_rgemmBatch_3d(cb_no_trans, cb_no_trans, 1, &A, &B, 0, &C, 1) == 6, GA_NO_ERROR == 0
<end of output>
Test time =   9.91 sec
```

**Comment by lamblin** [comment] 2017-09-12 15:01
The original error should be fixed by #522, however we should probably check why calling `error_sys(ctx->err, "malloc")` results in the Exception message being "malloc: No such file or directory".
It looks like we are reading from another message buffer that has not been cleaned up, but I don't know what the right fix would be.

**Comment by nouiz** [comment] 2017-09-12 15:23
I merged gh-522. I let @abergeron look for the strange error message.

**Comment by abergeron** [comment] 2017-09-12 16:01
#522 should fix this issue.  The problem was not a stale error message buffer but a stale errno value (since it's not reset on success).

**Closed** 2017-09-12 16:03 UTC
