### ISSUE TITLE
Overhead when using multiple GPU

### ISSUE THREAD

**Issue by trungnt13** [Theano/libgpuarray#148] opened 2016-04-03 00:11 UTC
I followed tutorial of theano for multiple-gpu: http://deeplearning.net/software/theano/tutorial/using_multi_gpu.html

This is my code:
```
x0 = theano.shared(np.random.rand(500, 1000), target='dev0')
x1 = theano.shared(np.random.rand(1000, 500), target='dev1')

s = time.time()
for i in range(10):
    T.dot(x0, x1).eval()
print(time.time() - s)

s = time.time()
for i in range(10):
    x = T.grad(T.mean(T.dot(x0, x1)), x0).eval()
print(time.time() - s)
```

There always enormous overhead for the first time I run the code:

|          | dot            | grad |
|--------|---------------|--------|
|First   | 8.76         | 33.1059319973 |
|Other | 0.57         |  1.53 |

How do I avoid this overhead ? 

Furthermore, does this backend support some MPI-like operator between GPUs (e.g all_reduce) ? If I use *transfer* to explicitly move data between GPUs, is it faster than *platoon* (zmp, or openMPI) ?

Can this backend be used for mutlple GPU via network ?

**Comment by abergeron** [comment] 2016-04-05 17:45
This would be more of a Theano issue.  Also this is not a bug report, so it would be more appropriate to discuss this on theano-users.

For the overhead, there are multiple issues and possible issues.  Let's start with the most obvious ones:
- The new backend is asynchronous, which means that eval() returning is not a guarantee that the computation is finished.  If you want to make sure that is the case, call the `sync()` method on the value returned by `eval()`.
- Having data on multiple devices means that Theano must make copies to bring everything on a single device to work on it.  This can in the worst case involve transfers through the host which will make everything syncrhonous

There is no support for MPI-like operators for now.  There may be in the future.  platoon has no support for transferring data between GPUs so I don't see how you can compare that to `transfer()`.

There are currently no plans for multi-machine support in this backend.  It may happen, but probably not anytime soon.

**Closed by abergeron** 2016-04-05 17:45 UTC
