### ISSUE TITLE
[check_array] undefined reference to `_ck_assert_failed'

### ISSUE THREAD

**Issue by trungnt13** [Theano/libgpuarray#147] opened 2016-04-01 15:58 UTC
I cannot make the library because of this error, I tried to install libcheck but the same thing happened.
As I know, this check_array only for unit test, is it possible to ignore this issue ?

```
Scanning dependencies of target check_array
[ 72%] Building C object tests/CMakeFiles/check_array.dir/main.c.o
[ 74%] Building C object tests/CMakeFiles/check_array.dir/check_array.c.o
[ 76%] Linking C executable check_array
CMakeFiles/check_array.dir/check_array.c.o: In function `setup':
check_array.c:(.text+0x21a): undefined reference to `_ck_assert_failed'
check_array.c:(.text+0x2b7): undefined reference to `_ck_assert_failed'
CMakeFiles/check_array.dir/check_array.c.o: In function `test_take1_ok':
check_array.c:(.text+0x3f1): undefined reference to `_ck_assert_failed'
check_array.c:(.text+0x4af): undefined reference to `_ck_assert_failed'
check_array.c:(.text+0x56d): undefined reference to `_ck_assert_failed'
CMakeFiles/check_array.dir/check_array.c.o:check_array.c:(.text+0x61b): more undefined references to `_ck_assert_failed' follow
collect2: error: ld returned 1 exit status
make[2]: *** [tests/check_array] Error 1
make[1]: *** [tests/CMakeFiles/check_array.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by trungnt13** [comment] 2016-04-01 15:59
ps: I checked if libcheck is installed properly

```
ldconfig -p | grep libcheck
	libcheck.so.0 (libc6,x86-64) => /usr/lib64/libcheck.so.0
	libcheck.so (libc6,x86-64) => /usr/lib64/libcheck.so
```

**Comment by nouiz** [comment] 2016-04-01 16:06
Can you try this PR:https://github.com/Theano/libgpuarray/pull/146

It could help your problem, but it still need work as it don't work in my
setup.

Keep us updated.

**Comment by trungnt13** [comment] 2016-04-02 00:12
I don't know what happened, but It worked perfectly for me. 
Everything built normally.

**Comment by abergeron** [comment] 2016-04-05 17:47
What is the version of the default libcheck?  As far as I know I require 0.10, but that may not be explicitly checked by the cmake script.

**Comment by trungnt13** [comment] 2016-04-07 13:39
Hi,

Both have the same version of libcheck 0.10.0, it is more bizarre since with the same libcheck, but I place it at different place will give different result (i.e. build by conda and without conda). 
I can only run the tests in a non-conda build but the include path and the library path all found in 2 cases.

**Comment by abergeron** [comment] 2016-04-08 16:04
Can you try this PR to see if it fixes things?

**Comment by nouiz** [comment] 2016-04-13 13:12
I merged that PR. Can you update libgpuarray, delete all the compile
directory (build and Build normally) and recompile?

**Comment by trungnt13** [comment] 2016-05-08 17:37
I recompiled pygpu using the newest revision: fc36a40
The configure code found libcheck, however, I don't know why it always fail to link the library during compiling. (another message from machine without libcheck: [link](http://pastebin.com/v87PL8eC)) 

```bash
-- The C compiler identification is GNU 4.9.1
-- Check for working C compiler: /appl/opt/gcc/4.9.1/bin/gcc
-- Check for working C compiler: /appl/opt/gcc/4.9.1/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /appl/opt/cuda/7.5 (found version "7.5") 
-- Found OpenCL: /appl/opt/cuda/7.5/lib64/libOpenCL.so  
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for mkstemp
-- Looking for mkstemp - found
Building with NVRTC
-- Looking for cublasSgemmEx
-- Looking for cublasSgemmEx - found
-- Could NOT find CLBLAS (missing:  CLBLAS_LIBRARIES CLBLAS_INCLUDE_DIRS) 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23") 
-- checking for one of the modules 'check'
-- Configuring done
-- Generating done
-- Build files have been written to: /homeappl/home/trungnt/appl_taito/libs/conda/conda-bld/work/Build
+ make
Scanning dependencies of target gpuarray
[  1%] Building C object src/CMakeFiles/gpuarray.dir/cache/lru.c.o
[  3%] Building C object src/CMakeFiles/gpuarray.dir/cache/twoq.c.o
[  5%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_types.c.o
[  6%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_error.c.o
[  8%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_util.c.o
[ 10%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer.c.o
[ 11%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array.c.o
[ 13%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array_blas.c.o
[ 15%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_kernel.c.o
[ 16%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_extension.c.o
[ 18%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_elemwise.c.o
[ 20%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_strl.c.o
[ 22%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_cuda.c.o
[ 23%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_blas_cuda_cublas.c.o
[ 25%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_opencl.c.o
[ 27%] Building C object src/CMakeFiles/gpuarray.dir/util/strb.c.o
[ 28%] Building C object src/CMakeFiles/gpuarray.dir/util/xxhash.c.o
[ 30%] Linking C shared library ../../lib/libgpuarray.so
[ 32%] Built target gpuarray
Scanning dependencies of target gpuarray-static
[ 33%] Building C object src/CMakeFiles/gpuarray-static.dir/cache/lru.c.o
[ 35%] Building C object src/CMakeFiles/gpuarray-static.dir/cache/twoq.c.o
[ 37%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_types.c.o
[ 38%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_error.c.o
[ 40%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_util.c.o
[ 42%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer.c.o
[ 44%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_array.c.o
[ 45%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_array_blas.c.o
[ 47%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_kernel.c.o
[ 49%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_extension.c.o
[ 50%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_elemwise.c.o
[ 52%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_strl.c.o
[ 54%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer_cuda.c.o
[ 55%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_blas_cuda_cublas.c.o
[ 57%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer_opencl.c.o
[ 59%] Building C object src/CMakeFiles/gpuarray-static.dir/util/strb.c.o
[ 61%] Building C object src/CMakeFiles/gpuarray-static.dir/util/xxhash.c.o
[ 62%] Linking C static library ../../lib/libgpuarray-static.a
[ 64%] Built target gpuarray-static
Scanning dependencies of target check_array
[ 66%] Building C object tests/CMakeFiles/check_array.dir/main.c.o
[ 67%] Building C object tests/CMakeFiles/check_array.dir/device.c.o
/homeappl/home/trungnt/appl_taito/libs/conda/conda-bld/work/tests/device.c: In function ‘setup’:
/homeappl/home/trungnt/appl_taito/libs/conda/conda-bld/work/tests/device.c:60:3: warning: implicit declaration of function ‘ck_assert_ptr_ne’ [-Wimplicit-function-declaration]
   ck_assert_ptr_ne(ctx, NULL);
   ^
[ 69%] Building C object tests/CMakeFiles/check_array.dir/check_array.c.o
[ 71%] Linking C executable check_array
CMakeFiles/check_array.dir/device.c.o: In function `setup':
device.c:(.text+0x191): undefined reference to `ck_assert_ptr_ne'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/check_array] Error 1
make[1]: *** [tests/CMakeFiles/check_array.dir/all] Error 2
make: *** [all] Error 2
Command failed: /bin/bash -x -e /homeappl/home/trungnt/appl_taito/libs/conda-recipes/pygpu/build.sh
```

**Comment by trungnt13** [comment] 2016-07-01 22:25
@nouiz is it possible to add an option that skip all the check ?

**Comment by nouiz** [comment] 2016-07-06 17:54
Probably. Do you want to try that? I don't have time now and @abergeron
will be back next week and it is him that know libcheck and cmake.

Could it be caused by different libcheck version?

In the mean time, it seem to compile correction for you when libcheck isn't
there. Can you compile without it to have something working now?

**Comment by abergeron** [comment] 2016-07-19 17:44
Can you launch the compile again with `make VERBOSE=1` so that we can see what command-line triggers the error.

**Comment by abergeron** [comment] 2017-02-07 20:20
This should be fixed now because the cmake script checks that the symbols we need are actually available.

**Closed by abergeron** 2017-02-07 20:20 UTC
