### ISSUE TITLE
libgpu make test fail and pygpu test fail on MacBook Pro

### ISSUE THREAD

**Issue by captainproton1971** [Theano/libgpuarray#346] opened 2017-02-05 03:09 UTC
Hi,
I'm trying to install libgpuarray on my MacBookPro11,3, OS/X 10.12.3 (16D32) and I'm running into trouble.  I'm using MacPorts python-27 in a virtual environment.  I've installed CUDA Driver Version: 8.0.63 with the CUDA toolkit 8.0.

The make seems to go well, but make test results in 7 failed tests.  [make test errors](http://pastebin.com/DtgNc1hS).  It seems that there's an awful lot of assertion errors, e.g., "check_elemwise.c:546:F:basic:test_basic_broadcast:0: Assertion 'ge != ((void*)0)' failed: ge == 0, ((void*)0) == 0".

Strangely(?), running the tests directly from /Build/tests/ only fails on test_buffer_collectives and test_collectives (I don't have nccl installed, so this wouldn't strike me as surprising):

/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:71:P:contig:test_contig_simple:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:133:P:contig:test_contig_f16:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:177:P:contig:test_contig_0:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:234:P:basic:test_basic_simple:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:297:P:basic:test_basic_f16:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:433:P:basic:test_basic_scalar:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:361:P:basic:test_basic_offset:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:495:P:basic:test_basic_remove1:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:563:P:basic:test_basic_broadcast:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:623:P:basic:test_basic_collapse:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:692:P:basic:test_basic_neg_strides:0: Passed
/Path/To/My/WorkingFolder/libgpuarray/tests/check_elemwise.c:737:P:basic:test_basic_0:0: Passed

Running setup.py (in the virtualenv) and running the test gives the output in the link below: seems to be a lot of errors re: contiguity.

[python test failures](http://pastebin.com/W7ZWYvMe)

I'd appreciate any thoughts you might have on what I'm doing wrong...

Thank you.

**Comment by abergeron** [comment] 2017-02-05 05:19
This might because of the "relaxed strides" from numpy 1.12.  I'll take a look later.  Since there are no other problems, your install is probably ok.

**Comment by captainproton1971** [comment] 2017-02-06 04:09
Thanks very much.  I haven't used python in quite a while, didn't appreciate the changes in numpy 1.12.  I'll go back to 1.11 for now.

**Comment by Dapid** [comment] 2017-02-07 12:34
I can confirm the same behaviour on Linux with Cuda.

If I understand the problem correctly, libgpuarray is yielding correct results, but the test is wrong.

**Comment by captainproton1971** [comment] 2017-02-09 20:58
Quick follow-up... reverting to numpy 1.11.3 cleared it all up.  I'll stay with this config for a while.  Thanks very much.

**Comment by abergeron** [comment] 2017-03-08 21:57
Yes, the results are correct.  Also, the errors with numpy 1.12 in the tests have been fixed now.

**Closed by abergeron** 2017-03-08 21:57 UTC
