### ISSUE TITLE
import error when importing gpuarray

### ISSUE THREAD

**Issue by kobecsb** [Theano/libgpuarray#353] opened 2017-02-13 10:07 UTC
Hi,
I installed libgpuarray according to the docs. (linux)
But when I import it, an import error occured. Does anybody else encounter such error? Thank you
BTW, when I'm testing pygpu like: 
`DEVICE="cuda0" python -c "import pygpu;pygpu.test()"`
It works well. No error encountered.

```
import theano
import theano.gpuarray
```
```
>>> import theano
>>> import theano.gpuarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/__init__.py", line 32, in <module>
    from . import fft, dnn, opt, nerv, extra_ops, multinomial, reduction
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/fft.py", line 14, in <module>
    from .opt import register_opt, op_lifter, register_opt2
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/opt.py", line 57, in <module>
    from .blocksparse import (GpuSparseBlockGemv, GpuSparseBlockOuter,
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blocksparse.py", line 91, in <module>
    gpu_sparse_block_gemv = GpuSparseBlockGemv(False)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blocksparse.py", line 31, in __init__
    COp.__init__(self, "blockgemv.c", "APPLY_SPECIFIC(blockgemv)")
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 1277, in __init__
    self.load_c_code(func_files)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 1357, in load_c_code
    "%s" % func_files[i])
ValueError: No valid section marker was found in file /search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blockgemv.c
```

**Comment by nouiz** [comment] 2017-02-13 14:50
What is the containt of the file /search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blockgemv.c

It could be corrupt.

**Comment by abergeron** [comment] 2017-02-13 16:22
This is not a pygpu/libgpuarray ticket and it has nothing to do with it.

The problem is most likely that your install of Theano is corrupted in some way.  You can post only the first line of the file @nouiz asked for and it should help us resolved the problem.

**Comment by kobecsb** [comment] 2017-02-14 01:45
Thank you for your help, abergeron and nouiz! The first line of 'blockgemv.c' is:
```
#section support_code_apply
```
@nouiz

**Comment by kobecsb** [comment] 2017-02-14 01:48
And, the entire file is like:
```
#section support_code_apply

int APPLY_SPECIFIC(blockgemv)(PyGpuArrayObject *o, PyGpuArrayObject *W,
                              PyGpuArrayObject *h, PyArrayObject *inputIdx,
                              PyArrayObject *outputIdx,
                              PyGpuArrayObject **_out,
                              PyGpuContextObject *ctx) {
  PyGpuArrayObject *out = *_out;
#ifdef INPLACE
  Py_XDECREF(out);
  out = o;
  Py_INCREF(out);
#else
  out = theano_try_copy(out, o);
  if (out == NULL) {
    // Error already set
    return -1;
  }
#endif

  gpudata **W_list = NULL;
  gpudata **inp_list = NULL;
  gpudata **out_list = NULL;
  size_t *offW = NULL;
  size_t *offInp = NULL;
  size_t *offOut = NULL;
  int err;

  err = gpublas_setup(ctx->ctx);
  if (err != GA_NO_ERROR) {
    PyErr_SetString(PyExc_RuntimeError, "Can't setup blas");
    return -1;
  }

  /* Prepare lists for the batch */
  size_t maxi = PyGpuArray_DIMS(h)[1];
  size_t maxj = PyGpuArray_DIMS(out)[1];
  size_t maxb = PyGpuArray_DIMS(out)[0];
  ssize_t h_str_0 = PyGpuArray_STRIDES(h)[0];
  ssize_t h_str_1 = PyGpuArray_STRIDES(h)[1];
  ssize_t o_str_0 = PyGpuArray_STRIDES(out)[0];
  ssize_t o_str_1 = PyGpuArray_STRIDES(out)[1];
  ssize_t W_str_0 = PyGpuArray_STRIDES(W)[0];
  ssize_t W_str_1 = PyGpuArray_STRIDES(W)[1];

  W_list = (gpudata **)calloc(sizeof(gpudata *), maxi * maxj * maxb);
  offW = (size_t *)calloc(sizeof(size_t), maxi * maxj * maxb);
  inp_list = (gpudata **)calloc(sizeof(gpudata *), maxi * maxj * maxb);
  offInp = (size_t *)calloc(sizeof(size_t), maxi * maxj * maxb);
  out_list = (gpudata **)calloc(sizeof(gpudata *), maxi * maxj * maxb);
  offOut = (size_t *)calloc(sizeof(size_t), maxi * maxj * maxb);
  if (W_list == NULL || offW == NULL ||
      inp_list == NULL || offInp == NULL ||
      out_list == NULL || offOut == NULL) {
    free(W_list);
    free(offW);
    free(inp_list);
    free(offInp);
    free(out_list);
    free(offOut);
    PyErr_NoMemory();
    return -1;
  }

  for (size_t i = 0; i < maxi; i++) {
    for (size_t j = 0; j < maxj; j++) {
      for (size_t b = 0; b < maxb; b++) {
        size_t p = i + j * maxi + b * maxi * maxj;
        inp_list[p] = h->ga.data;
        offInp[p] = b * h_str_0 + i * h_str_1 + h->ga.offset;
        out_list[p] = out->ga.data;
        offOut[p] = b * o_str_0 + j * o_str_1 + out->ga.offset;
        W_list[p] = W->ga.data;
        offW[p] = *(DTYPE_INPUT_3 *)PyArray_GETPTR2(inputIdx, b, i) * W_str_0 +
          *(DTYPE_INPUT_4 *)PyArray_GETPTR2(outputIdx, b, j) * W_str_1 +
          W->ga.offset;
      }
    }
  }

  cb_transpose transA = cb_no_trans;
  size_t lda = PyGpuArray_STRIDES(W)[2] / gpuarray_get_elsize(W->ga.typecode);
  if (lda == 1) {
    transA = cb_trans;
    lda = PyGpuArray_STRIDES(W)[3] / gpuarray_get_elsize(W->ga.typecode);
  }

  if (out->ga.typecode == GA_FLOAT) {
    err = gpublas_sgemvBatch(cb_fortran, transA,
                             PyGpuArray_DIMS(out)[2],
                             PyGpuArray_DIMS(h)[2], 1,
                             W_list, offW, lda,
                             inp_list, offInp, PyGpuArray_STRIDES(h)[2] / gpuarray_get_elsize(h->ga.typecode),
                             1, out_list, offOut, PyGpuArray_STRIDES(out)[2] / gpuarray_get_elsize(out->ga.typecode),
                             PyGpuArray_DIMS(out)[1] * PyGpuArray_DIMS(h)[1] * PyGpuArray_DIMS(out)[0], 0);
  } else if (out->ga.typecode == GA_DOUBLE) {
    err = gpublas_dgemvBatch(cb_fortran, transA,
                             PyGpuArray_DIMS(out)[2],
                             PyGpuArray_DIMS(h)[2], 1,
                             W_list, offW, lda,
                             inp_list, offInp, PyGpuArray_STRIDES(h)[2] / gpuarray_get_elsize(h->ga.typecode),
                             1, out_list, offOut, PyGpuArray_STRIDES(out)[2] / gpuarray_get_elsize(out->ga.typecode),
                             PyGpuArray_DIMS(out)[1] * PyGpuArray_DIMS(h)[1] * PyGpuArray_DIMS(out)[0], 0);
  } else if (out->ga.typecode == GA_HALF) {
    err = gpublas_sgemvBatch(cb_fortran, transA,
                             PyGpuArray_DIMS(out)[2],
                             PyGpuArray_DIMS(h)[2], 1,
                             W_list, offW, lda,
                             inp_list, offInp, PyGpuArray_STRIDES(h)[2] / gpuarray_get_elsize(h->ga.typecode),
                             1, out_list, offOut, PyGpuArray_STRIDES(out)[2] / gpuarray_get_elsize(out->ga.typecode),
                             PyGpuArray_DIMS(out)[1] * PyGpuArray_DIMS(h)[1] * PyGpuArray_DIMS(out)[0], 0);
  } else {
    err = GA_INVALID_ERROR;
  }
  
  free(W_list);
  free(offW);
  free(inp_list);
  free(offInp);
  free(out_list);
  free(offOut);
  if (err != GA_NO_ERROR) {
    PyErr_SetString(PyExc_RuntimeError, "gemvBatch failed");
    return -1;
  }
  *_out = out;
  return 0;
}


```

**Comment by abergeron** [comment] 2017-02-14 03:18
This is what it is supposed to be, so it doesn't seem to be a corrupted file.  I am perplexed since the code is looking for `#section` and it is there.

**Comment by kobecsb** [comment] 2017-02-14 03:24
I'm confused too. When I test pygpu like
```DEVICE="cuda0" python -c "import pygpu;pygpu.test()"``` , 
it seems to be correct. The output is like:
```
pygpu is installed in /search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/pygpu-0.6.0-py2.7-linux-x86_64.egg/pygpu
NumPy version 1.11.3
NumPy relaxed strides checking option: False
NumPy is installed in /search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/numpy
Python version 2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 20 2016, 23:09:15) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7
*** Testing for Tesla K40m
.............................................................................................................................................................................................................................................................................................................................................................................................................................................
```

**Comment by abergeron** [comment] 2017-02-14 03:28
The problem is in the code for COp in theano, under theano/gof/op.py.

Maybe you can try to add a bunch of prints of the values in there to help see what is going on.

**Comment by abergeron** [comment] 2017-02-14 04:17
Your diagnosis is ok, but I fail to understand how the section_re can fail to match the first line of the file, which is clearly the right pattern for it.

**Comment by kobecsb** [comment] 2017-02-14 05:41
I think the regex doesn't match the code indeed.
I've done some unit test:
1. dumped the self.func_codes into a json file, namely "code.file"
2. wrote a test python script as following
3. test the result
```
import re
import json

codes = None
with open('code.file') as inp:
    codes = json.load(inp)
code = codes[0].encode('utf-8')

section_re = re.compile(r'^#section ([a-zA-Z0-9_]+)$', re.MULTILINE)
backward_re = re.compile(
    r'^THEANO_(APPLY|SUPPORT)_CODE_SECTION$',
    re.MULTILINE)
if backward_re.search(code):
    print 'backward'
elif section_re.search(code):
    print 'forward'
else:
    print 'not matched'
```

The output is 'not matched'. But if we change the regex to ```r'^#section ([a-zA-Z0-9_\r]+)$'```, the output is "forward", because there are some '\r' at the end of each line. I'm not sure whether this is the original intention.

**Comment by abergeron** [comment] 2017-02-14 06:09
There shouldn't be \r in that file.  The proper fix is to remove them, but I have no idea why they are there.

**Comment by abergeron** [comment] 2017-02-14 06:12
I just checked the git master and there are no \r in the file on git, so the problem was in transit somewhere.  How did you install Theano?

**Comment by kobecsb** [comment] 2017-02-14 06:18
Oh. I cloned Theano to my local machine which is of windows OS,  and then use scp to copy the main directory to my server. I had to do this because there's no Internet connection on my server. Maybe that's the problem. But even if we tackled the '\r' issue, the ```ValueError: Unknown section type (in file /search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blockger.c): support_code_apply``` would appear.

**Comment by nouiz** [comment] 2017-02-14 13:42
I think we should detect if \r are in the file and raise and error or
correct it directly with a warning.

Otherwise, as you saw more fixes will be needed, all stuff that detect up
to the end of the line must be reviewed and make a to support it.

Le mar. 14 févr. 2017 01:18, Justin Chan <notifications@github.com> a
écrit :

**Comment by nouiz** [comment] 2017-02-14 13:42
Is there the equivalent of dos2unix on Windows or Python?

**Comment by abergeron** [comment] 2017-02-14 16:52
If we want to fix the regexp to support \r in the line endings, it should look like this:
```
section_re = re.compile(r'^#section ([a-zA-Z0-9_]+)\r?$', re.MULTILINE)
```
Where the \r is outside of the capturing group.

**Comment by abergeron** [comment] 2017-02-14 17:48
This is addressed in https://github.com/Theano/Theano/issues/5540

**Closed by abergeron** 2017-02-14 17:48 UTC
Labels: Theano Issue
