### ISSUE TITLE
libgpuarray test script fails

### ISSUE THREAD

**Issue by folagit** [Theano/libgpuarray#254] opened 2016-09-12 14:56 UTC
During the make process, I get the following warnings, which I assume result in some of the failed tests:

```
CMake Warning at src/CMakeLists.txt:159 (add_library):
  Cannot generate a safe runtime search path for target gpuarray because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libOpenCL.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.


CMake Warning at tests/CMakeLists.txt:55 (add_executable):
  Cannot generate a safe runtime search path for target check_elemwise
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libOpenCL.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.


CMake Warning at tests/CMakeLists.txt:47 (add_executable):
  Cannot generate a safe runtime search path for target check_util because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libOpenCL.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.


CMake Warning at tests/CMakeLists.txt:59 (add_executable):
  Cannot generate a safe runtime search path for target check_error because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libOpenCL.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.


CMake Warning at tests/CMakeLists.txt:63 (add_executable):
  Cannot generate a safe runtime search path for target check_buffer because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libOpenCL.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.


CMake Warning at tests/CMakeLists.txt:51 (add_executable):
  Cannot generate a safe runtime search path for target check_array because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libOpenCL.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.


CMake Warning at tests/CMakeLists.txt:43 (add_executable):
  Cannot generate a safe runtime search path for target check_types because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libOpenCL.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.

================================================

Here are the results of the libgpuarray install test:

================================================

sudo make test
Running tests...
Test project /home/fa6/git/libgpuarray/Build
    Start 1: test_types
1/6 Test #1: test_types .......................   Passed    0.02 sec
    Start 2: test_util
2/6 Test #2: test_util ........................   Passed    0.02 sec
    Start 3: test_array
3/6 Test #3: test_array .......................***Failed    0.02 sec
    Start 4: test_elemwise
4/6 Test #4: test_elemwise ....................***Failed    0.02 sec
    Start 5: test_error
5/6 Test #5: test_error .......................   Passed    0.02 sec
    Start 6: test_buffer
6/6 Test #6: test_buffer ......................***Failed    0.02 sec

50% tests passed, 3 tests failed out of 6

Total Test time (real) =   0.13 sec

The following tests FAILED:
      3 - test_array (Failed)
      4 - test_elemwise (Failed)
      6 - test_buffer (Failed)
Errors while running CTest
Makefile:116: recipe for target 'test' failed
make: *** [test] Error 8
```

I've tried suggestions to update $LD_LIBRARY_PATH and run ldconfig but this does not resolve the issue. 

I am running Ubuntu 16.04, with CUDA 8.0, CUDANN 5.1.5. gcc and g++ all point to alternate versions suggested by theano install documentation.

Any help with this issue will be greatly appreciated.

thanks.

**Comment by nouiz** [comment] 2016-09-12 15:15
I think it is a duplicate of https://github.com/Theano/libgpuarray/issues/247. We don't have time to work on the openCL back-end. Many things are missing. We need people outside our group to come and help finish it.

**Comment by abergeron** [comment] 2016-09-12 15:53
The CMake warnings have nothing to do with the failures and should be harmless.  The problem with the tests is that you didn't specify GPUARRAY_TEST_DEVICE or DEVICE as an environment variable to specify on which device to test (or you did and it gets removed because of sudo).

Try running `DEVICE=cuda0 make test`

**Comment by folagit** [comment] 2016-09-12 17:41
abergeron's suggestion helped to resolve this. Thank you.

**Closed** 2017-02-07 22:26 UTC
