### ISSUE TITLE
 pip install -user . does not work

### ISSUE THREAD

**Issue by rizar** [Theano/libgpuarray#160] opened 2016-04-22 21:27 UTC
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR:theano.gof.opt:Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{0.0})
ERROR:theano.gof.opt:node: GpuFromHost<None>(TensorConstant{0.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR:theano.gof.opt:TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/u/bahdanau/.local/lib/python2.7/site-packages/theano/gof/opt.py", line 1773, in process_node
    replacements = lopt.transform(node)
  File "/u/bahdanau/.local/lib/python2.7/site-packages/theano/tensor/opt.py", line 5884, in constant_folding
    no_recycling=[])
  File "/u/bahdanau/.local/lib/python2.7/site-packages/theano/gof/op.py", line 978, in make_thunk
    no_recycling)
  File "/u/bahdanau/.local/lib/python2.7/site-packages/theano/gof/op.py", line 881, in make_c_thunk
    output_storage=node_output_storage)
  File "/u/bahdanau/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/u/bahdanau/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/u/bahdanau/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1587, in cthunk_factory
    key = self.cmodule_key()
  File "/u/bahdanau/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1284, in cmodule_key
    header_dirs=self.header_dirs(),
  File "/u/bahdanau/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1051, in header_dirs
    ret += x.c_header_dirs()
  File "/u/bahdanau/.local/lib/python2.7/site-packages/theano/sandbox/gpuarray/type.py", line 457, in c_header_dirs
    return [pygpu.get_include(), numpy.get_include()]
  File "/u/bahdanau/.local/lib/python2.7/site-packages/pygpu/__init__.py", line 4, in get_include
    assert os.path.exists(os.path.join(p, 'gpuarray_api.h'))
AssertionError

**Comment by nouiz** [comment] 2016-04-29 18:25
I think the problem is that you need to install first libgpuarray:

http://deeplearning.net/software/libgpuarray/installation.html#step-by-step-install

Can you confirm you didn't installed it? If so, I'll make the error message better.

**Comment by abergeron** [comment] 2016-07-19 17:47
This does not look like a libgpuarray error.  Also, it's more than two months old so I'll close it.

**Closed by abergeron** 2016-07-19 17:47 UTC
