### ISSUE TITLE
pygpu.init("cuda0") throws TypeError: can't concat bytes to str

### ISSUE THREAD

**Issue by neuralyzer** [Theano/libgpuarray#139] opened 2016-03-11 09:51 UTC
I compiled and installed libgpuarray and pygpu. I then tried to run the tests. OpenCl is not available on my computer. Therefore I wanted to set the context to "cuda0" first. However, I get this concatenation error. I'm running Anaconda Python 3.5.

**Comment by abergeron** [comment] 2016-03-11 16:54
Thanks for the report, I'll have to look at this in more detail later since we do want to support python 3.  In the meantime, I know that python 2 works.

**Comment by neuralyzer** [comment] 2016-03-11 17:02
Interestingly the error occurs for "cuda0" on the first call of pygpu.init. When I call pygpu.init("cuda1") it works the first time. The second time I get again "TypeError: can't concat bytes to string". Similar for the other GPU devices. I have set device=gpu im my .theanorc.

**Comment by nouiz** [comment] 2016-03-11 17:03
Don't mix gpu with cuda. This is 2 different GPU back-en. Use device=cuda*
instead of device=gpu. Maybe it will fix your problem.

Which OS do you use?

**Comment by neuralyzer** [comment] 2016-03-11 17:08
I've just tried to set device=cuda0. However, I get the same error.

**Comment by neuralyzer** [comment] 2016-03-11 17:08
I use Linux.

**Comment by neuralyzer** [comment] 2016-03-11 17:16
I think it is somehow about repeatedly calling pygpu.init() with the same device. Maybe the message tells me that the device is already used?

**Comment by abergeron** [comment] 2016-03-11 17:59
Are you using pygpu through theano?  In that case, what @nouiz said is true.

But If you are just using pygpu, then it doesn't matter what is in your .theanorc.

**Comment by neuralyzer** [comment] 2016-03-11 18:38
I used pygpu directly. I actually tried to run pygpu.test() after installation. Then I got these errors. I did not import theano.

**Comment by abergeron** [comment] 2016-03-11 18:42
Ok, then I'll have to reproduce this, but I don't have the time right now.  I might get to it next week.

**Comment by abergeron** [comment] 2016-07-19 17:42
I tried to reproduce this and I can't.  Can you give me a detailed list of commands (or code) that give you this error?

**Comment by neuralyzer** [comment] 2016-07-20 06:13
Hi, I tried to reproduce the error. I don't get it anymore but instead a different one. Steps to reproduce:

1. Clone the libgpuarray repo and install into ~/libgpuarray
2. I do export LD_LIBRARY_PATH=~/libgpuarray
(my LD_LIBRARY_PATH was empty before that)
3. start python, import pygpu
4. pygpu.test()

gives

```
ERROR: Failure: GpuArrayException (Invalid value or operation: 0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/anaconda3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "~/anaconda3/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "~/anaconda3/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "~/anaconda3/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "~/anaconda3/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "~/anaconda3/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "~/anaconda3/lib/python3.5/site-packages/pygpu-0.2.1-py3.5-linux-x86_64.egg/pygpu/tests/test_tools.py", line 5, in <module>
    from .support import (guard_devsup, rand, check_flags, check_meta, check_all,
  File "~/anaconda3/lib/python3.5/site-packages/pygpu-0.2.1-py3.5-linux-x86_64.egg/pygpu/tests/support.py", line 32, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 562, in pygpu.gpuarray.init (pygpu/gpuarray.c:8359)
  File "pygpu/gpuarray.pyx", line 508, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:7974)
  File "pygpu/gpuarray.pyx", line 965, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12332)
pygpu.gpuarray.GpuArrayException: Invalid value or operation: 0
```

**Comment by abergeron** [comment] 2016-07-20 20:47
This (albeit obscure) error means that there is no device "0" on your machine or that it is unavailable for some reason.

What is the output of nvidia-smi on that machine?

**Comment by neuralyzer** [comment] 2016-07-21 06:00
Here is the output of nvidia-smi

```
+------------------------------------------------------+                       
| NVIDIA-SMI 352.79     Driver Version: 352.79         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M2090         On   | 0000:48:00.0     Off |                    0 |
| N/A   N/A   P12    28W / 225W |     10MiB /  5375MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M2090         On   | 0000:49:00.0     Off |                    0 |
| N/A   N/A   P12    28W / 225W |     10MiB /  5375MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla M2090         On   | 0000:4A:00.0     Off |                    0 |
| N/A   N/A   P12    28W / 225W |     10MiB /  5375MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla M2090         On   | 0000:4B:00.0     Off |                    0 |
| N/A   N/A   P12    28W / 225W |     10MiB /  5375MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla M2090         On   | 0000:55:00.0     Off |                    0 |
| N/A   N/A   P12    28W / 225W |     10MiB /  5375MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla M2090         On   | 0000:56:00.0     Off |                    0 |
| N/A   N/A   P12    29W / 225W |     10MiB /  5375MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla M2090         On   | 0000:57:00.0     Off |                    0 |
| N/A   N/A   P12    28W / 225W |     10MiB /  5375MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla M2090         On   | 0000:58:00.0     Off |                    0 |
| N/A   N/A   P12    29W / 225W |     10MiB /  5375MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by senarvi** [comment] 2016-10-19 10:49
I'm also unable to initialize CUDA devices with libgpuarray. I've been using the CUDA backend without problems. This is what I try:

    nvidia-smi
    export THEANO_FLAGS="contexts=dev0->cuda0"
    python -c 'import theano'

And this is the output:

    Wed Oct 19 13:37:48 2016
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |===============================+======================+======================|
    |   0  Tesla K80           On   | 0000:05:00.0     Off |                    0 |
    | N/A   22C    P8    26W / 149W |      0MiB / 11439MiB |      0%   E. Process |
    +-------------------------------+----------------------+----------------------+
    |   1  Tesla K80           On   | 0000:06:00.0     Off |                    0 |
    | N/A   29C    P8    28W / 149W |      0MiB / 11439MiB |      0%   E. Process |
    +-------------------------------+----------------------+----------------------+
    |   2  Tesla K80           On   | 0000:09:00.0     Off |                    0 |
    | N/A   24C    P8    26W / 149W |      0MiB / 11439MiB |      0%   E. Process |
    +-------------------------------+----------------------+----------------------+
    |   3  Tesla K80           On   | 0000:0A:00.0     Off |                    0 |
    | N/A   30C    P8    29W / 149W |      0MiB / 11439MiB |      0%   E. Process |
    +-------------------------------+----------------------+----------------------+
    |   4  Tesla K80           On   | 0000:84:00.0     Off |                    0 |
    | N/A   23C    P8    27W / 149W |      0MiB / 11439MiB |      0%   E. Process |
    +-------------------------------+----------------------+----------------------+
    |   5  Tesla K80           On   | 0000:85:00.0     Off |                    0 |
    | N/A   32C    P8    28W / 149W |      0MiB / 11439MiB |      0%   E. Process |
    +-------------------------------+----------------------+----------------------+
    |   6  Tesla K80           On   | 0000:88:00.0     Off |                    0 |
    | N/A   22C    P8    26W / 149W |      0MiB / 11439MiB |      0%   E. Process |
    +-------------------------------+----------------------+----------------------+
    |   7  Tesla K80           On   | 0000:89:00.0     Off |                    0 |
    | N/A   31C    P8    30W / 149W |      0MiB / 11439MiB |      0%   E. Process |
    +-------------------------------+----------------------+----------------------+
    
    +-----------------------------------------------------------------------------+
    | Processes:                                                       GPU Memory |
    |  GPU       PID  Type  Process name                               Usage      |
    |=============================================================================|
    |  No running processes found                                                 |
    +-----------------------------------------------------------------------------+
    ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
    Traceback (most recent call last):
      File "/.../lib/python3.5/site-packages/Theano-0.9.0.dev3-py3.5.egg/theano/gpuarray/__init__.py", line 132, in <module>
        init_dev(d.strip(), n.strip())
      File "/.../lib/python3.5/site-packages/Theano-0.9.0.dev3-py3.5.egg/theano/gpuarray/__init__.py", line 67, in init_dev
        sched=config.gpuarray.sched)
      File "pygpu/gpuarray.pyx", line 583, in pygpu.gpuarray.init (pygpu/gpuarray.c:8686)
      File "pygpu/gpuarray.pyx", line 529, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8301)
      File "pygpu/gpuarray.pyx", line 986, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12659)
    pygpu.gpuarray.GpuArrayException: Invalid value or operation: 0`

**Comment by senarvi** [comment] 2016-11-21 10:03
I updated Theano and libgpuarray today and now it works for me.

**Comment by nouiz** [comment] 2016-11-25 18:41
thanks for the update. I'll close this issue. If other people have problems, make sure to update libgpuarray and if that don't fix it, open a new issue.

**Closed by nouiz** 2016-11-25 18:41 UTC
