### ISSUE TITLE
cmake unable to find libcheck

### ISSUE THREAD

**Issue by ksze** [Theano/libgpuarray#455] opened 2017-06-19 04:22 UTC
It appears that the cmake config is unable to find libcheck, even if I have built and installed locally the latest libcheck release (0.11.0)  from source.

I have built and installed libcheck 0.11.0 as follows:
- `/home/ksze/include/check.h`
- `/home/ksze/include/check_stdint.h`
- `/home/ksze/lib/libcheck.a`
- `/home/ksze/lib/libcheck.la`
- `/home/ksze/lib/libcheck.so`
- `/home/ksze/lib/libcheck.so.0`
- `/home/ksze/lib/libcheck.so.0.0.0`
- `/home/ksze/lib/pkgconfig/check.pk`

I could run pkg-config to find it:

    $ PKG_CONFIG_PATH=/home/ksze/lib/pkgconfig pkg-config --cflags --libs check;
    -pthread -I/home/ksze/include -L/home/alvafit/lib -lcheck

However, when I run cmake to configure libgpuarray, I get this:

    $ cd ~/git-repositories/libgpuarray/Build
    $ PKG_CONFIG_PATH=/home/ksze/lib/pkgconfig/ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/ksze
    Tests disabled because Check was not found
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/ksze/git-repositories/libgpuarray/Build

I had also tried using the libcheck (0.9.10-6ubuntu) from the Ubuntu apt repo, but I got the same result:

    $ dpkg -l check
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name               Version        Architecture   Description
    +++-==================-==============-==============-=========================================
    ii  check:amd64        0.9.10-6ubuntu amd64          unit test framework for C

OS: Ubuntu 14.04.5 Server 64-bit
CMake: CMake 3.7.1 from cmake.org's binary distribution
Using tag v0.6.5 of the libgpuarray git repository.

**Comment by abergeron** [comment] 2017-06-19 17:08
The tests require libcheck 0.10 or higher so that is why the ubuntu package doesn't work.

As for why your local install doesn't work, I don't know.  Exporting PKG_CONFIG_PATH should work.

Can you try `PKG_CONFIG_PATH=/home/ksze/lib/pkgconfig pkg-config --modversion`

**Comment by deepali-c** [comment] 2017-06-20 06:14
Even I see this same issue. 

I have installed check using `apt-get`

```
$ dpkg -l check
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version            Architecture       Description
+++-==========================-==================-==================-=========================================================
ii  check:amd64                0.10.0-3           amd64              unit test framework for C
```
However, with `cmake `I get the following output:
```
 $ cmake .. -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for mkstemp
-- Looking for mkstemp - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for one of the modules 'check'
-- Performing Test CHECK_FUNCS
-- Performing Test CHECK_FUNCS - Failed
Tests disabled because Check was not found
-- Configuring done
-- Generating done
```

**Comment by ksze** [comment] 2017-06-20 06:18
@abergeron 

    $ PKG_CONFIG_PATH=/home/ksze/lib/pkgconfig pkg-config --modversion check
    0.11.0

**Comment by abergeron** [comment] 2017-06-21 14:20
@deepali-c Your problem is that it finds libcheck, but fails to find the functions it needs inside it and thus rejects the library it found.

As for the original problem of CMake not respecting PKG_CONFIG_PATH, I will admit I have no idea why it doesn't.  If somebody has time to look into this, I will take patches.

**Comment by deepali-c** [comment] 2017-06-29 14:24
@abergeron Thanks for pointing out that it is due to failure to find the required function. I had missed that.

I was trying to understand the reason and the I executed the code under the CHECK_C_SOURCE_COMPILES seperately and realized that it needs to link to lpthread. 

So I added lpthread as a required library:
```
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index 74cf17f..13841be 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -19,7 +19,7 @@ endif()
 if(CHECK_FOUND)
   set(CMAKE_REQUIRED_FLAGS ${CHECK_C_FLAGS} ${CHECK_LDFLAGS_OTHERS})
   set(CMAKE_REQUIRED_INCLUDES ${CHECK_INCLUDE_DIRS})
-  set(CMAKE_REQUIRED_LIBRARIES ${CHECK_LIBRARIES})
+  set(CMAKE_REQUIRED_LIBRARIES ${CHECK_LIBRARIES} pthread)
   CHECK_C_SOURCE_COMPILES(
     "#include <check.h>
      int main() {
```
and got success:
```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for one of the modules 'check'
-- Performing Test CHECK_FUNCS
-- Performing Test CHECK_FUNCS - Success
```

**Comment by abergeron** [comment] 2017-06-29 14:37
Hmmm.  Normally the pkgconfig file will have those extra flags/libraries already and we don't need to manually add any whne we query it.  Can you check if any of the output variables have the required 
`-lpthread`?

**Comment by deepali-c** [comment] 2017-06-29 14:44
Yes, I had tried printing the output variables and it does not show `-lpthread`.

```
-- Checking for one of the modules 'check'
-- CHECK_INCLUDE_DIRS:
-- CHECK_LIBRARIES:         check_picrtmsubunit
-- CHECK_FOUND:         1
-- CHECK_INCLUDE_DIRS-NOTFOUND:
-- CHECK_C_FLAGS:
-- CHECK_LDFLAGS_OTHERS:
-- Performing Test CHECK_FUNCS
-- Performing Test CHECK_FUNCS - Success
```

**Comment by deepali-c** [comment] 2017-06-30 12:57
The `cmake `version is:
```
$ cmake --version
cmake version 3.5.1
```

**Comment by abergeron** [comment] 2017-07-03 16:14
Can you print out CHECK_LDFLAGS?

**Comment by deepali-c** [comment] 2017-07-04 03:48
The output for `CHECK_LDFLAGS `is : 
`-- CHECK_LDFLAGS:         -lcheck_pic-pthread-lrt-lm-lsubunit`

**Comment by abergeron** [comment] 2017-07-04 04:02
So we should probably add CHECK_LDFLAGS to the CMAKE LDFLAGS for tests.

**Comment by deepali-c** [comment] 2017-07-04 04:41
I have tried the following:
1.  Added `CHECK_LDFLAGS` to the `CMAKE_REQUIRED_FLAGS `:
   ```
  -  set(CMAKE_REQUIRED_FLAGS ${CHECK_C_FLAGS} ${CHECK_LDFLAGS_OTHERS})
    +  set(CMAKE_REQUIRED_FLAGS ${CHECK_C_FLAGS} ${CHECK_LDFLAGS}  ${CHECK_LDFLAGS_OTHERS})
```
But this does not work. The console output is:
```
-- CHECK_LDFLAGS:         -lcheck_pic-pthread-lrt-lm-lsubunit
-- CHECK_LDFLAGS_OTHERS:
-- CMAKE_REQUIRED_FLAGS:         -lcheck_pic-pthread-lrt-lm-lsubunit
-- Performing Test CHECK_FUNCS
-- Performing Test CHECK_FUNCS - Failed
```

2. Added `CHECK_LDFLAGS `to `CMAKE_REQUIRED_LIBRARIES `
```
-  set(CMAKE_REQUIRED_LIBRARIES ${CHECK_LIBRARIES})
+  set(CMAKE_REQUIRED_LIBRARIES ${CHECK_LIBRARIES} ${CHECK_LDFLAGS} )
```
This works:
```
-- CHECK_LDFLAGS:         -lcheck_pic-pthread-lrt-lm-lsubunit
-- CHECK_LDFLAGS_OTHERS:
-- CMAKE_REQUIRED_FLAGS:
-- Performing Test CHECK_FUNCS
-- Performing Test CHECK_FUNCS - Success
```

**Comment by abergeron** [comment] 2017-07-04 18:36
I'm not sure adding it to CMAKE_REQUIRED_LIBRARIES is the proper fix, but it is a step in the right direction.  However, I don't have a lot of time this week to come up with a fix.  And the problem is that this is a bit like playing whack-a-mole since a fix for one configuration tends to break others.

Still if you feel up to do a PR, that would be welcome.

**Comment by deepali-c** [comment] 2017-07-05 04:24
Yes even I am not sure if adding it to `CMAKE_REQUIRED_LIBRARIES  `is  proper here.  I wonder why cmake is not returning lpthread in `CHECK_LIBRARIES`.

**Comment by deepali-c** [comment] 2017-07-05 09:49
I was checking for further alternatives for this and I realized that `pkgconfig `also returns `<XPREFIX>_VERSION`and this in my case is:
```
-- Checking for one of the modules 'check'
-- CHECK_VERSION:         0.10.0
-- CHECK_INCLUDE_DIRS:
```
So can we use this to verify that the required version of check is available or not? This way we can avoid checking the version using the `CHECK_C_SOURCE_COMPILES`.

**Comment by deepali-c** [comment] 2017-07-05 10:11
I continued to check the current working of the fall back case and observed that it also fails to detect the functions and gives:
```
-- Found Check: /usr/local/lib/libcheck.so
-- CHECK_VERSION:
-- CHECK_INCLUDE_DIRS:         /usr/local/include
-- CHECK_LIBRARIES:         /usr/local/lib/libcheck.so
-- CHECK_FOUND:         1
-- CHECK_INCLUDE_DIRS-NOTFOUND:
-- CHECK_C_FLAGS:
-- CHECK_LDFLAGS:
-- CHECK_LDFLAGS_OTHERS:
-- CMAKE_REQUIRED_FLAGS:
-- Performing Test CHECK_FUNCS
-- Performing Test CHECK_FUNCS - Failed
Tests disabled because Check was not found
```

**Comment by deepali-c** [comment] 2017-07-05 14:19
I have tried the following for this:
1. Check the version for the `check `package returned by `pkgconfig `and set `CHECK_FOUND to 0` if version is less than `0.10.0`. 
2. If pkgconfig fails then execute the fall-back code, with further modification to check for availability of required libraries. 
Sharing the patch here:
[check_check_version.txt](https://github.com/Theano/libgpuarray/files/1124959/check_check_version.txt)

**Comment by abergeron** [comment] 2017-07-05 14:46
I'm mostly ok with your patch, if you can make that a PR.

**Comment by deepali-c** [comment] 2017-07-10 04:35
Thank you @abergeron  for accepting the fix. 

@ksze , Could you please use the latest `libgpuarray `code and check if you still face the issue?

**Comment by nouiz** [comment] 2017-08-01 19:19
Can this be closed? I think https://github.com/Theano/libgpuarray/pull/475/files fixed this issue.

**Comment by abergeron** [comment] 2017-08-01 19:44
That commit doesn't fix the issue reported here which is that you can't specify the path that pkgconfig will look in when running cmake.

If we can confirm that that works, then I would consider this fixed.

**Comment by nouiz** [comment] 2018-01-11 19:12
can we close this now? I think there was more libcheck fix since the last comment.

**Comment by abergeron** [comment] 2018-01-11 19:16
I'm not sure what has changed since then, but we can probably close this for now.  If some people have problems with libcheck again, we can reopen this or create a new issue.

**Closed by abergeron** 2018-01-11 19:16 UTC
