### ISSUE TITLE
Impossible to test API/ABI version from kernel code

### ISSUE THREAD

**Issue by dhdaines** [Theano/libgpuarray#565] opened 2018-01-17 16:10 UTC
Hi,

I have some kernel code that I'd like to maintain compatibility with libgpuarray 0.6 and 0.7.  You would *think* that it would work to just put this:

```
#include <gpuarray/config.h>
#if GPUARRAY_API_VERSION == 2
#include <cluda.h>
#endif 

```
But that doesn't work!  I'm just speculating here but it appears that either NVCC doesn't see the libgpuarray header files, or its preprocessor is broken and can't do #if tests.

Instead I have to test for the new-style DTYPE_INPUT_N / DTYPE_OUTPUT_N macros, which is less than ideal.

Is there any way to fix this?  Is it a problem with libgpuarray or CUDA?

**Comment by nouiz** [comment] 2018-01-17 16:22
I'll let @abergeron answer your question. But I think using the test of the
new style macro is fine.

Why do you want to support both? We don't support 0.6 anymore ourself.

Out of curiosity, which kernel are you building?

**Comment by abergeron** [comment] 2018-01-18 03:40
The problem is that we use NVRTC for compilation and it doesn't see any headers that we haven't previously registered.  As it's not able to find <gpuarray/config.h> that `#include` will not work.

 If you are doing this from Theano, you can check for the theano version since Theano 0.9 == libgpuarray 0.6 and Theano 1.0 == libgpuarray 0.7.

**Comment by dhdaines** [comment] 2018-01-23 23:02
Hi,

We want to support 0.6.9 because Theano 1.0.1 is slower than 0.9.0 and
doesn't support the old backend, which is also faster and uses less GPU
memory than the new backend.

But ... our custom code (which does a specific kind of max-pooling) was
written for the new backend.

Oddly enough the new backend also seems to be faster in 0.9.0 and also
doesn't throw out of memory errors.

Still trying to figure out what is going on here, maybe I will file another
bug report once I do.


On Wed, Jan 17, 2018 at 11:22 AM, Frédéric Bastien <notifications@github.com
> wrote:

> I'll let @abergeron answer your question. But I think using the test of the
> new style macro is fine.
>
> Why do you want to support both? We don't support 0.6 anymore ourself.
>
> Out of curiosity, which kernel are you building?
>
> On Wed, Jan 17, 2018 at 11:10 AM David Huggins Daines <

**Comment by nouiz** [comment] 2018-01-30 02:01
It is not normal that 0.9 is faster then 1.0.1.

Can you run both version with Theano profiler(use Theano flag profile=True)
and give me the output?

Fred

**Comment by nouiz** [comment] 2018-05-11 00:41
no news in a long time, so closing.

**Closed by nouiz** 2018-05-11 00:41 UTC
