### ISSUE TITLE
SIP breaks library loading (with the system python) on macOS

### ISSUE THREAD

**Issue by 2shou** [Theano/libgpuarray#336] opened 2017-01-30 14:04 UTC
I have a new macbook pro(2016) and tried to install theano with gpu support on it.
but, after I finished installing libgpuarray and theano(0.9.0beta1.dev), and test by [check1.py](http://deeplearning.net/software/theano/tutorial/using_gpu.html#testing-theano-with-gpu), it shows like this:
```
bogon:Downloads 2shou$ THEANO_FLAGS=mode=FAST_RUN,device=opencl0:0,floatX=float32 python check1.py
python: dlopen: OpenCL.framework/OpenCL: No such file or directory
Segmentation fault: 11
```
is there anything wrong?

**Comment by abergeron** [comment] 2017-01-30 19:03
This should fix the segfault: https://github.com/Theano/libgpuarray/pull/338

However it will do nothing for the root of the problem which is that the OpenCL library can't be loaded for some reason.

 * Which version of macOS that you have?
 * What is the output of `mdfind -name OpenCL.framework`?

**Comment by 2shou** [comment] 2017-01-31 02:27
@abergeron 
my macos version is 10.12.3.
```
bogon:~ 2shou$ mdfind -name OpenCL.framework
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenCL.framework
/System/Library/Frameworks/OpenCL.framework
```

**Comment by abergeron** [comment] 2017-01-31 04:03
I have the same version and it loads and runs fine.

Can you try to run this: `DYLD_PRINT_LIBRARIES_POST_LAUNCH=1 python -c 'import pygpu; pygpu.init("opencl0:0")'` and print the output

**Comment by 2shou** [comment] 2017-02-01 14:54
it shows the same:
```
2shou$ DYLD_PRINT_LIBRARIES_POST_LAUNCH=1 python -c 'import pygpu; pygpu.init("opencl0:0")'
python: dlopen: OpenCL.framework/OpenCL: No such file or directory
```

**Comment by abergeron** [comment] 2017-02-01 16:26
This should print a large list of libraries that are loaded by python (even before it gets to trying and failing on OpenCL).  If it really prints nothing, something is wrong with your version of python.  At this point, though I don't know what.

**Comment by 2shou** [comment] 2017-02-02 15:08
@abergeron 
I have tried to run this and it printed a large list of libraries but crashed finally:
```
2shou$ DEVICE=opencl0:0 python -c "import pygpu;pygpu.test()"
pygpu is installed in /Library/Python/2.7/site-packages/pygpu-0.6.0-py2.7-macosx-10.12-intel.egg/pygpu
NumPy version 1.12.0
NumPy relaxed strides checking option: True
NumPy is installed in /Users/guoze/Library/Python/2.7/lib/python/site-packages/numpy
Python version 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
nose version 1.3.7
python: dlopen: OpenCL.framework/OpenCL: No such file or directory
Segmentation fault: 11
```

**Comment by abergeron** [comment] 2017-02-02 20:39
The crash is fixed in master.

Also, this is not what I asked.  Please run this exact command and post the full output:
```
DYLD_PRINT_LIBRARIES_POST_LAUNCH=1 python -c 'import pygpu; pygpu.init("opencl0:0")'
```

**Comment by 2shou** [comment] 2017-02-03 03:29
@abergeron 
I tried to reinstall libgpuarray by user account and it shows more messages:
```
2shou$ DYLD_PRINT_LIBRARIES_POST_LAUNCH=1 python -c 'import pygpu; pygpu.init("opencl0:0")'
python: dlopen: OpenCL.framework/OpenCL: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pygpu/gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9212)
  File "pygpu/gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8903)
  File "pygpu/gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13265)
pygpu.gpuarray.GpuArrayException: Error loading library: 0
```

**Comment by abergeron** [comment] 2017-02-03 03:47
Which python do you use?  Is it the system python or a custom compiled one?

**Comment by 2shou** [comment] 2017-02-03 04:06
the python version is `2.7.10`, the system one, path: `/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python`.

**Comment by abergeron** [comment] 2017-02-03 04:36
Apparently this is a problem with SIP (System Integrity Protection) and it is also the cause of you no getting any debugging messages from dyld.

One workaround that appears to work with multiple people is to create a virtualenv with the system python and this disables SIP for that python.

Another option is to install an alternative python from somewhere else.  We usually recommend Anaconda (or its little brother Miniconda).

The proper fix is apparently to hardcode the full path to the framework in the library code.  This can work for OpenCL since it is a standard library and therefore not likely to move.  But the other libraries (like clBLAS or the cuda drivers) are less fixed and would be harder to fix.

I'll add a note in the mac-specific instructions about that.

**Comment by 2shou** [comment] 2017-02-03 14:14
I have tried to install anaconda and finally it shows debugging messages from dyld with clblas import error:
```
Downloads 2shou$ DYLD_PRINT_LIBRARIES_POST_LAUNCH=1 python -c 'import pygpu; pygpu.init("opencl0:0")'
dyld: loaded: /System/Library/CoreServices/Encodings/libSimplifiedChineseConverter.dylib
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_locale.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/pygpu-0.6.0-py2.7-macosx-10.7-x86_64.egg/pygpu/gpuarray.so
dyld: loaded: /Users/guoze/Downloads/libgpuarray/lib/libgpuarray.2.dylib
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_ctypes.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_struct.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/math.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/numpy/core/multiarray.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/numpy/core/../../../../libmkl_intel_lp64.dylib
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/numpy/core/../../../../libmkl_intel_thread.dylib
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/numpy/core/../../../../libmkl_core.dylib
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/numpy/core/../../../../libiomp5.dylib
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/datetime.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/numpy/core/umath.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/operator.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_collections.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/itertools.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_heapq.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/cPickle.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/cStringIO.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_functools.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/time.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/grp.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_io.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/binascii.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/../../libz.1.dylib
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_hashlib.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/../../libssl.1.0.0.dylib
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/../../libcrypto.1.0.0.dylib
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_random.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/fcntl.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/numpy/linalg/lapack_lite.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/numpy/linalg/_umath_linalg.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/future_builtins.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/numpy/fft/fftpack_lite.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/numpy/random/mtrand.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/strop.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/pygpu-0.6.0-py2.7-macosx-10.7-x86_64.egg/pygpu/_elemwise.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_socket.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_ssl.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_scproxy.so
dyld: loaded: /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
dyld: loaded: /usr/lib/libnetwork.dylib
dyld: loaded: /usr/lib/libbsm.0.dylib
dyld: loaded: /usr/lib/libpcap.A.dylib
dyld: loaded: /usr/lib/libcoretls.dylib
dyld: loaded: /usr/lib/libcoretls_cfhelpers.dylib
dyld: loaded: /System/Library/Frameworks/Security.framework/Versions/A/Security
dyld: loaded: /usr/lib/libxar.1.dylib
dyld: loaded: /usr/lib/libsqlite3.dylib
dyld: loaded: /usr/lib/libpam.2.dylib
dyld: loaded: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
dyld: loaded: /usr/lib/libOpenScriptingUtil.dylib
dyld: loaded: /usr/lib/libbz2.1.0.dylib
dyld: loaded: /usr/lib/libxml2.2.dylib
dyld: loaded: /usr/lib/liblzma.5.dylib
dyld: loaded: /usr/lib/libenergytrace.dylib
dyld: loaded: /usr/lib/system/libkxld.dylib
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_json.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/zlib.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/pyexpat.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/site-packages/markupsafe/_speedups.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/select.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_multiprocessing.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/_hotshot.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/resource.so
dyld: loaded: /Users/guoze/anaconda2/lib/python2.7/lib-dynload/parser.so
dyld: loaded: /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
dyld: loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
dyld: loaded: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
dyld: loaded: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
dyld: loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
dyld: loaded: /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
dyld: loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
dyld: loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
dyld: loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
dyld: loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
dyld: loaded: /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
dyld: loaded: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
dyld: loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
dyld: loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSync.framework/Versions/A/ColorSync
dyld: loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
dyld: loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
dyld: loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
dyld: loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
dyld: loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
dyld: loaded: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
dyld: loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
dyld: loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
dyld: loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
dyld: loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
dyld: loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
dyld: loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
dyld: loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
dyld: loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
dyld: loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
dyld: loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
dyld: loaded: /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
dyld: loaded: /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
dyld: loaded: /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
dyld: loaded: /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
dyld: loaded: /usr/lib/libarchive.2.dylib
dyld: loaded: /usr/lib/liblangid.dylib
dyld: loaded: /usr/lib/libCRFSuite.dylib
dyld: loaded: /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
dyld: loaded: /usr/lib/libmecabra.dylib
dyld: loaded: /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
dyld: loaded: /usr/lib/libmarisa.dylib
dyld: loaded: /usr/lib/libChineseTokenizer.dylib
dyld: loaded: /usr/lib/libcmph.dylib
dyld: loaded: /usr/lib/libiconv.2.dylib
dyld: loaded: /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
dyld: loaded: /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
dyld: loaded: /usr/lib/libcompression.dylib
dyld: loaded: /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
dyld: loaded: /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
dyld: loaded: /usr/lib/libxslt.1.dylib
dyld: loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
dyld: loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
dyld: loaded: /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
dyld: loaded: /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
dyld: loaded: /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
dyld: loaded: /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
dyld: loaded: /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
dyld: loaded: /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
dyld: loaded: /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
dyld: loaded: /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
dyld: loaded: /usr/lib/libcups.2.dylib
dyld: loaded: /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
dyld: loaded: /System/Library/Frameworks/GSS.framework/Versions/A/GSS
dyld: loaded: /usr/lib/libresolv.9.dylib
dyld: loaded: /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
dyld: loaded: /usr/lib/libheimdal-asn1.dylib
dyld: loaded: /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
dyld: loaded: /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
dyld: loaded: /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
dyld: loaded: /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
dyld: loaded: /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
dyld: loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
dyld: loaded: /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
dyld: loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
dyld: loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
dyld: loaded: /System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/libcldcpuengine.dylib
dyld: loaded: /usr/lib/libcrypto.0.9.8.dylib
dyld: loaded: /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
dyld: loaded: /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
dyld: loaded: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
dyld: loaded: /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
dyld: loaded: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
dyld: loaded: /System/Library/PrivateFrameworks/GPUCompiler.framework/libmetal_timestamp.dylib
dyld: loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
dyld: loaded: /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
dyld: loaded: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
dyld: loaded: /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
dyld: loaded: /usr/lib/libFosl_dynamic.dylib
dyld: loaded: /System/Library/PrivateFrameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
dyld: loaded: /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
dyld: loaded: /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
dyld: loaded: /System/Library/Extensions/AppleIntelSKLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelSKLGraphicsGLDriver
dyld: loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
dyld: loaded: /System/Library/PrivateFrameworks/GPUSupport.framework/Versions/A/Libraries/libGPUSupportMercury.dylib
dyld: loaded: /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/AMDRadeonX4000GLDriver
dyld: loaded: /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib
dyld: loaded: /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
dyld: loaded: cl_kernels
python: dlopen: libclBLAS.dylib: No such file or directory
python: dlopen: libclblast.dylib: No such file or directory
```
how to fix it?

**Comment by abergeron** [comment] 2017-02-03 19:01
Now it should be fine.  The "errors" only show that you don't have any blas library for OpenCL so blas operations will not be available, but the rest should work ok.

**Comment by 2shou** [comment] 2017-02-04 04:23
so how to install the blas library for OpenCL? I want to use gpu in theano.
```
Downloads 2shou$ THEANO_FLAGS=mode=FAST_RUN,device=opencl0:0,floatX=float32 python check1.py
python: dlopen: libclBLAS.dylib: No such file or directory
python: dlopen: libclblast.dylib: No such file or directory
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/Users/guoze/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/Users/guoze/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/Users/guoze/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 100, in init_dev
    pygpu.blas.gemm(0, tmp, tmp, 0, tmp, overwrite_c=True)
  File "pygpu/blas.pyx", line 129, in pygpu.blas.gemm (pygpu/blas.c:3354)
  File "pygpu/blas.pyx", line 44, in pygpu.blas.pygpu_blas_rgemm (pygpu/blas.c:2011)
GpuArrayException: ('Unsupported operation', 5)
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 1.590474 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu
```

**Comment by abergeron** [comment] 2017-02-05 05:14
You have to install either clBLAS (https://github.com/clMathLibraries/clBLAS) or CLBlast (https://github.com/CNugteren/CLBlast)

**Comment by 2shou** [comment] 2017-02-05 09:30
@abergeron 
I tried to install both and tested successfully by `pygpu.init()`.
However, running with theano still failed with these messages:
```
2shou$ THEANO_FLAGS=mode=FAST_RUN,device=opencl0:0,floatX=float32 python check1.py
CLBlast: Run-time error: -55
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/Users/guoze/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/Users/guoze/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/Users/guoze/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 100, in init_dev
    pygpu.blas.gemm(0, tmp, tmp, 0, tmp, overwrite_c=True)
  File "pygpu/blas.pyx", line 129, in pygpu.blas.gemm (pygpu/blas.c:3354)
  File "pygpu/blas.pyx", line 44, in pygpu.blas.pygpu_blas_rgemm (pygpu/blas.c:2011)
GpuArrayException: ('(clblast) error in blas call, no details for now.', 11)
```

**Comment by nouiz** [comment] 2017-02-07 16:28
The OpenCL back-end in Theano is missing work to be usable. So be warned
that this could be the first problem and not the last.

Are you ready to help us make it work? We don't have time to work on it now.

**Comment by abergeron** [comment] 2017-09-12 19:51
This is on macOS which is not supported anymore.

**Closed by abergeron** 2017-09-12 19:51 UTC
