### ISSUE TITLE
pygpu.gpuarray.GpuArrayException: Unaligned array / Binary mode not supported any more

### ISSUE THREAD

**Issue by jagiella** [Theano/libgpuarray#432] opened 2017-05-10 09:41 UTC
Using keras/theano with the new gpuarray backend, the following error occured:

```python
Traceback (most recent call last):
  File "newBackend.py", line 38, in <module>
    model.fit( x, y)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 856, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1498, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1152, in _fit_loop
    outs = f(ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1158, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 683, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:9990)
  File "pygpu/gpuarray.pyx", line 396, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:7083)
pygpu.gpuarray.GpuArrayException: Unaligned array
Apply node that caused the error: GpuContiguous(InplaceGpuDimShuffle{3,2,0,1}.0)
Toposort index: 58
Inputs types: [GpuArrayType<None>(float32, (False, False, False, False))]
Inputs shapes: [(4, 1, 11, 11)]
Inputs strides: [(4, 9223372036854775807, 176, 16)]
Inputs values: ['not shown']
Outputs clients: [[Shape(GpuContiguous.0), Shape_i{3}(GpuContiguous.0), Shape_i{2}(GpuContiguous.0), Shape_i{0}(GpuContiguous.0), GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```
Code to reproduce the problem:
```python
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dropout, Dense
import numpy as np
x = np.random.random( size=(100, 1, 200, 300)).astype('float32')
y = np.random.random( size=(100, 3)).astype('float32')
model = Sequential([
	Conv2D( 4, (11,11), activation='relu', padding='same', input_shape=x.shape[1:]),
	MaxPooling2D( (2,2)),
	Conv2D( 8, (7,7), activation='relu', padding='same'),
	MaxPooling2D( (2,2)),
	Conv2D( 16, (5,5), activation='relu', padding='same'),
	MaxPooling2D( (2,2)),
	Conv2D( 32, (3,3), activation='relu', padding='same'),
	MaxPooling2D( (2,2)),
	Conv2D( 64, (3,3), activation='relu', padding='same'),
	MaxPooling2D( (2,2)),
	#Conv2D( 128, (3,3), activation='relu', padding='same'),
	#MaxPooling2D( (2,2)),
	#Conv2D( 256, (3,3), activation='relu', padding='same'),
	#MaxPooling2D( (2,2)),
	Flatten(),
	Dropout(0.05),
	Dense(128, activation='relu'),
	Dropout(0.05),
	Dense(y.shape[1], activation='softmax')
])
#print( model.summary())
model.compile( loss='categorical_crossentropy', optimizer='adadelta', metrics=['accuracy'])
model.fit( x, y)
```

**Comment by jagiella** [comment] 2017-05-10 10:21
Since last revision (version=0.6.5) the error message changed from `Unaligned array` to `Binary mode not supported any more`:
```python
Using Theano backend.
Using cuDNN version 5105 on context None
Mapped name None to device cuda: GeForce GTX 1070 (0000:01:00.0)
Epoch 1/10
Traceback (most recent call last):
  File "newBackend.py", line 38, in <module>
    model.fit( x, y)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 856, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1498, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1152, in _fit_loop
    outs = f(ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1158, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 683, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:9990)
  File "pygpu/gpuarray.pyx", line 396, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:7083)
pygpu.gpuarray.GpuArrayException: Binary mode not supported any more
Apply node that caused the error: GpuContiguous(InplaceGpuDimShuffle{3,2,0,1}.0)
Toposort index: 52
Inputs types: [GpuArrayType<None>(float32, (False, False, False, False))]
Inputs shapes: [(4, 1, 11, 11)]
Inputs strides: [(4, 9223372036854775807, 176, 16)]
Inputs values: ['not shown']
Outputs clients: [[Shape(GpuContiguous.0), Shape_i{3}(GpuContiguous.0), Shape_i{2}(GpuContiguous.0), Shape_i{0}(GpuContiguous.0), GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by nouiz** [comment] 2017-05-10 15:48
This got 2fixes. It you update keras it should should it. I don't know if
you need keras dev version of the last release.

Updating Theano to the dev version would also fix it.

**Comment by nouiz** [comment] 2017-05-10 15:48
Update Theano to the dev version.

**Comment by jagiella** [comment] 2017-05-16 08:18
Updating Theano to the latest version from git does not solve the issue...
```bash
sudo -H python -m pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
Successfully installed Theano-0.9.0
```
The error transforms to:
```python
Using Theano backend.
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
In file included from /tmp/try_flags_Q3q20i.c:4:0:
/usr/include/cudnn.h:63:26: fatal error: driver_types.h: No such file or directory
compilation terminated.

Mapped name None to device cuda: GeForce GTX 1070 (0000:01:00.0)
Epoch 1/10
Traceback (most recent call last):
  File "newBackend.py", line 38, in <module>
    model.fit( x, y)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 868, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1503, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1155, in _fit_loop
    outs = f(ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1196, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 683, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:9990)
  File "pygpu/gpuarray.pyx", line 396, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:7083)
pygpu.gpuarray.GpuArrayException: 
Apply node that caused the error: GpuContiguous(GpuSubtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 72
Inputs types: [GpuArrayType<None>(float32, 4D)]
Inputs shapes: [(4, 1, 11, 11)]
Inputs strides: [(4, 9223372036854775807, -176, -16)]
Inputs values: ['not shown']
Outputs clients: [[GpuCorrMM{valid, (1, 1), (1, 1)}(GpuContiguous.0, GpuContiguous.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by nouiz** [comment] 2017-05-16 12:34
Do you have coffee that reproduce that?

**Comment by jagiella** [comment] 2017-05-16 12:43
coffee?
The same error happens on all machines I tried it on. All of them Ubuntu 16.04 though.

**Comment by nouiz** [comment] 2017-05-16 13:01
I love coffee:) Just android auto correction for "code" Do you have small
code that reproduce that? I don't see the problem here and it would need
more investigation.

**Comment by jagiella** [comment] 2017-05-16 13:48
A minimal example already reproducing the error is
```python
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dropout, Dense
import numpy as np
x = np.random.random( size=(100, 1, 200, 300)).astype('float32')
y = np.random.random( size=(100, 3)).astype('float32')
model = Sequential([
	Conv2D( 4, (11,11), activation='relu', padding='valid', input_shape=x.shape[1:]),
	MaxPooling2D( (2,2)),
	Flatten(),
	Dense(128, activation='relu'),
	Dense(y.shape[1], activation='softmax')
])
print( model.summary())
model.compile( loss='categorical_crossentropy', optimizer='adadelta', metrics=['accuracy'])
model.fit( x, y)
```

**Comment by nouiz** [comment] 2017-05-16 14:22
This give me another error. What are your Theano flags?

**Comment by nouiz** [comment] 2017-05-16 14:27
I have this error:

```
$ THEANO_FLAGS=device=cuda,floatX=float32 python test.py 
Using Theano backend.
/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/skcuda/cublas.py:282: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')
/u/bastienf/repos/theano/gpuarray/dnn.py:135: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to version 5.1.
  warnings.warn("Your cuDNN version is more recent than "
Using cuDNN version 6005 on context None
Mapped name None to device cuda: GeForce GTX 750 (0000:05:00.0)
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    Dense(y.shape[1], activation='softmax')
  File "/u/bastienf/repos/keras/models.py", line 407, in __init__
    self.add(layer)
  File "/u/bastienf/repos/keras/models.py", line 475, in add
    output_tensor = layer(self.outputs[0])
  File "/u/bastienf/repos/keras/engine/topology.py", line 569, in __call__
    self.build(input_shapes[0])
  File "/u/bastienf/repos/keras/layers/core.py", line 827, in build
    constraint=self.kernel_constraint)
  File "/u/bastienf/repos/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/u/bastienf/repos/keras/engine/topology.py", line 391, in add_weight
    weight = K.variable(initializer(shape), dtype=dtype, name=name)
  File "/u/bastienf/repos/keras/initializers.py", line 208, in __call__
    dtype=dtype, seed=self.seed)
  File "/u/bastienf/repos/keras/backend/theano_backend.py", line 2091, in random_uniform
    return rng.uniform(shape, low=minval, high=maxval, dtype=dtype)
  File "/u/bastienf/repos/theano/sandbox/rng_mrg.py", line 796, in uniform
    size)
ValueError: ('The specified size contains a dimension with value <= 0', (-1900, 128))
```

It happen that input_dim is -1900

**Comment by jagiella** [comment] 2017-05-16 14:46
my `.theanorc`-file looks as follows:
```
[cuda]
root = /usr/local/cuda-8.0

[global]
floatX=float32
device=gpu

[nvcc]
flags=-D_FORCE_INLINES

[lib]
cnmem = 0.
```

**Comment by nouiz** [comment] 2017-05-16 14:47
The problem is in keras. Can you open a keras issue and link it here? Probably an older keras version work in the mean time, but be sure to open an issue and follow up to get the master of keras fixed.

The problem is that the layer Conv2d generate a negative shape. It use tensorflow dimensions ordering even if in keras config file I have:

```
{
    "image_dim_ordering": "th", 
    "epsilon": 1e-07, 
    "floatx": "float32", 
    "backend": "theano"
}
```

**Comment by nouiz** [comment] 2017-05-16 14:48
You don't use the master of Theano, but an old version:

device=gpu

this is removed from the current master of Theano. There is a new GPU back-end:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

**Comment by jagiella** [comment] 2017-05-16 14:50
yeah because I changed back as I need it to actually run! The tests I did and errors I encountered happened with the dev version and `device=cuda`

**Comment by nouiz** [comment] 2017-05-16 14:53
Did you reverted Keras to get a working copy?

I don't know what is happening with keras, but with that keras config, it
don't use Theano, but tensoflow and ignore the backend I set...

**Comment by jagiella** [comment] 2017-05-16 14:56
As I need it for work, I switched back. But I am highly interested in getting the new backend (theano / libgpuarray) to work before the support for the current will drop out in v0.10 :)

**Comment by nouiz** [comment] 2017-05-16 15:09
As I said, the current problem you have are in keras and not Theano. So we
can't help. Make an issue there and link to here. I'll see it and put some
code I used in Theano to help investigate this and find the earliest case
of the problem in the graph.

**Comment by nouiz** [comment] 2017-06-05 17:10
I think this was fixed (the unaligned array error) in Theano and Keras. So closing. If there still other thing left, open a new issue or reopen this one if this is exactly the same problem.

**Closed by nouiz** 2017-06-05 17:10 UTC

**Comment by jagiella** [comment] 2017-06-06 13:35
I don't think, that it's actually solved. The error message just changed from `pygpu.gpuarray.GpuArrayException: Unaligned array` to `pygpu.gpuarray.GpuArrayException:`. The error location and context still remains the same. 

See the parallel Theano issue [#5945](https://github.com/Theano/Theano/issues/5945)
